services:

  php:
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - php

  database:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  database_data: